branches:
  except:
    - gh-pages

install:
  - set PATH=C:\Python36;%PATH%
  - cmake --version

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCLI_SINGLE_FILE_TESTS=ON -DCMAKE_GENERATOR="Visual Studio 14 2015"
  - cmake --build .

test_script:
  - ctest --output-on-failure

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/0185e91c5d989a476d7b
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
